package com.example.kintai.shared.kernel.contract;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * DomainEvent 基底クラスの単体テスト
 *
 * <p>eventId の自動生成、occurredAt の自動設定、getEventType() のサブクラス実装を検証する。</p>
 */
@DisplayName("DomainEvent 基底クラス テスト")
class DomainEventTest {

    /**
     * テスト用の具象DomainEvent
     */
    private static class TestEvent extends DomainEvent {
        @Override
        public String getEventType() {
            return "TEST_EVENT";
        }
    }

    /**
     * テスト用の具象DomainEvent（別の型）
     */
    private static class AnotherTestEvent extends DomainEvent {
        @Override
        public String getEventType() {
            return "ANOTHER_TEST_EVENT";
        }
    }

    @Test
    @DisplayName("eventId が自動生成される（非null）")
    void eventId_isAutoGenerated() {
        TestEvent event = new TestEvent();

        // eventId が非null であることを検証する
        assertNotNull(event.getEventId(),
                "eventId は自動生成されるべき");
    }

    @Test
    @DisplayName("occurredAt が自動設定される（現在時刻付近）")
    void occurredAt_isAutoSet() {
        Instant before = Instant.now();
        TestEvent event = new TestEvent();
        Instant after = Instant.now();

        // occurredAt が非null であることを検証する
        assertNotNull(event.getOccurredAt(),
                "occurredAt は自動設定されるべき");

        // occurredAt が before 〜 after の範囲内であることを検証する
        assertFalse(event.getOccurredAt().isBefore(before),
                "occurredAt は生成前の時刻より後であるべき");
        assertFalse(event.getOccurredAt().isAfter(after),
                "occurredAt は生成後の時刻より前であるべき");
    }

    @Test
    @DisplayName("2つのインスタンスは異なる eventId を持つ")
    void twoInstances_haveDifferentEventIds() {
        TestEvent event1 = new TestEvent();
        TestEvent event2 = new TestEvent();

        // 異なる eventId であることを検証する
        assertNotEquals(event1.getEventId(), event2.getEventId(),
                "各インスタンスは異なる eventId を持つべき");
    }

    @Test
    @DisplayName("getEventType がサブクラスの値を返す")
    void getEventType_returnsSubclassValue() {
        TestEvent event = new TestEvent();
        AnotherTestEvent anotherEvent = new AnotherTestEvent();

        // 各サブクラスが自身のイベント型を返すことを検証する
        assertEquals("TEST_EVENT", event.getEventType());
        assertEquals("ANOTHER_TEST_EVENT", anotherEvent.getEventType());
    }

    @Test
    @DisplayName("テスト用コンストラクタで eventId と occurredAt を外部指定できる")
    void testConstructor_acceptsExternalValues() {
        UUID customId = UUID.randomUUID();
        Instant customTime = Instant.parse("2026-01-01T00:00:00Z");

        // テスト用コンストラクタを使用する具象クラス
        DomainEvent event = new DomainEvent(customId, customTime) {
            @Override
            public String getEventType() {
                return "CUSTOM";
            }
        };

        // 指定した値が設定されていることを検証する
        assertEquals(customId, event.getEventId(),
                "外部指定した eventId が設定されるべき");
        assertEquals(customTime, event.getOccurredAt(),
                "外部指定した occurredAt が設定されるべき");
    }
}
