spring:
  application:
    name: kintai

  # デフォルトプロファイル（明示指定がなければdevを使用）
  profiles:
    default: dev

  # JPA共通設定
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Tokyo

  # Flyway共通設定
  flyway:
    enabled: true
    locations: classpath:db/migration

# サーバー設定
server:
  port: 8080
